# Generated by Django 5.1.6 on 2025-02-15 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["id", "assigned_to"], name="TaskApp_tas_id_0701d0_idx"
            ),
        ),
    ]
