# Generated by Django 5.1.6 on 2025-02-15 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0002_task_taskapp_tas_id_0701d0_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="task",
            name="TaskApp_tas_id_0701d0_idx",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["id", "status", "due_date", "assigned_to"],
                name="TaskApp_tas_id_be2759_idx",
            ),
        ),
    ]
