# Generated by Django 5.1.6 on 2025-02-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0003_remove_task_taskapp_tas_id_0701d0_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(),
        ),
    ]
