# Generated by Django 5.1.6 on 2025-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["id"], name="UserApp_cus_id_831edb_idx"),
        ),
    ]
