# Generated by Django 5.1.6 on 2025-02-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0002_alter_customuser_options_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="UserApp_cus_id_831edb_idx",
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["id", "role"], name="UserApp_cus_id_25df81_idx"),
        ),
    ]
